name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
        - CSharpNine/CSharpNine
        - CSharpNine-Finished/CSharpNine
        - CSharpTen/CSharpTen
        - CSharpTen-Finished/CSharpTen
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for ${{ matrix.project }}
      run: dotnet restore ./${{ matrix.project }}.csproj
    - name: Build for ${{ matrix.project }}
      run: dotnet build ./${{ matrix.project }}.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
